version: '3.8'

services:
  yaozhi-server:
    build: .
    image: jixiannet/yaozhi:latest
    ports:
      - "7100:7100"
    volumes:
      - .:/app                 # 挂载当前目录到容器内 /app
      - ./tasks.db:/app/tasks.db   # 持久化 SQLite 数据库文件
      - ./uploads:/app/uploads  # 持久化上传的文件
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
